### ISSUE TITLE
Cell block blue doors becoming locked again

### ISSUE THREAD

**Issue by HPetch** [seylorx1/BugsOfDischordia#41] opened 2021-08-09 13:41 UTC
Expected Result:
The player should open blue doors by walking into them with a blue keycard in the inventory.

Actual Result:
If the player returns to the cell block floor from the warehouse, or is caught by a drone after retrieving the blue key card, the blue doors leading to the stairs to the warehouse become locked until you restart the game application.

Steps to Reproduce:
1. Start the game in the cell block
2. Collect the blue keycard from the chest in the cell block level
3. Interact with both blue doors with the keycard, they should both open
4. Get caught by a drone and restart at a checkpoint
5. Attempt to walk through the blue doors - they are now closed and don't unlock

Build:
DARE.BETA.b36

**Comment by seylorx1** [comment] 2021-08-10 11:28
This is intended behaviour, however we noticed the UI didn't update with the keycards correctly. I'll mark this as 'wontfix', but we're currently fixing the UI bug! :)

**Closed as completed** 2021-08-10 11:28 UTC
Labels: wontfix, bug - gameplay, jira
